server:
  port: 8082
spring:
  application:
    name: demo
  ########MySQL
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imooc-demo?useSSL=false&serverTimezone=UTC
    password: 123456
    username: root
  session:
    store-type: none  #暂时关掉Session
security:  #四K瑞提
  basic:
    enabled: false  #关闭身份验证